name: Build

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    push:
        branches: ['master']
    pull_request:

jobs:
    build:
        runs-on: windows-latest

        strategy:
            matrix:
                include:
                    - target: x86_64-pc-windows-msvc
                      arch: x64
                    - target: i686-pc-windows-msvc
                      arch: x86

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: 'npm'
                  architecture: ${{matrix.arch}}
            - name: Rust Cache
              uses: Swatinem/rust-cache@v2.5.1
            - name: Install Dependencies
              run: npm ci
            - name: Build
              run: npm run build -- --target ${{matrix.target}}
            - name: Test
              run: npm test
